export const sentence = {
  byMe: "React app developed by Antonio Jiménez",
  titleApp: "Employee management App",
  addEmployee: "Add employee",
  editEmployee: "Edit Employee",
  deleteEmployee: "Delete Employee",
  newEmployee: "New Employee",
  placeholderSearch: "Type a name...",
  nameShort: "Your name is too short",
  nameLarge: "Your name is too long",
  surnameShort: "Your surname is too short",
  surnameLarge: "Your surname is too long",
  requiredName: "Please enter a name",
  requiredSurname: "Please enter a surname",
  requiredPosition: "Please, select a position",
  requiredBirthday: "Please enter a date of birth",
  name: "Name",
  surname: "Surname",
  position: "Position",
  birthday: "Birthday",
  dateOfBirthday: "Date of birthday",
  accept: "Accept",
  cancel: "Cancel",
  select: "Select",
  removeQuestion: "Which employee do you want to remove?",
  editQuestion: "Which employee do you want to edit?",
  msgNewEmployee: "welcome to our family!",
  msgUpdateEmployee: "we have updated your data.",
  msgDeleteEmploye: "we will miss you, good luck."
}